### ISSUE TITLE
TypeError: t is null

### ISSUE THREAD

**Issue by b-d-m-p** [prismicio/gatsby-blog#3]
Followed your tutorial below, but getting an error in the browser.
https://user-guides.prismic.io/en/articles/2933292-sample-blog-with-api-based-cms-gatsby-js

`TypeError: t is null` 

Any ideas?

**Comment by levimykel** [comment]
Hi @b-d-m-p, I'm not sure what the issue is off the top of my head. Can you give me more information?
1. At what step do you receive this error?
2. Can you send the full error message and stack trace?
3. What is the URL for your Prismic repository?

Also, for better support you can reach out to us through our chat support system in your Prismic repository or on the prismic.io website. We might be able to better help you from there.

**Comment by levimykel** [comment]
Closed due to inactivity.
